#pragma once

#define BUCKET_GRID_RESOLUTION 512
#define BUCKET_GRID_SIZE 1024

#define BUCKET_GRID_RESOLUTION_BUILD 128
#define BUCKET_GRID_RESOLUTION_ENEMY 64
#define BUCKET_GRID_RESOLUTION_RESOURCE 128