#pragma once
#define ENVIRONMENT_DEBUG_SIZE 9

enum class EnvironmentDebugMode : char {
	NONE,
	MAIN_GRID,
	INF_UNITS_NUMBER_PER_PLAYER,
	INF_UNITS_INFLUENCE_PER_PLAYER,
	INF_BUILDING_INFLUENCE_PER_PLAYER,
	INF_RESOURCE,
	INF_ATTACK_INFLUENCE_PER_PLAYER,
	INF_DEFENCE_INFLUENCE_PER_PLAYER,
	INF_ECON_INFLUENCE_PER_PLAYER
};
