#pragma once
enum class EnvironmentDebugMode : char {
	NONE = 0,
	MAIN_GRID,
	
	INF_UNITS_NUMBER_PER_PLAYER,
	INF_UNITS_INFLUENCE_PER_PLAYER,
	INF_BUILDING_INFLUENCE_PER_PLAYER,
	INF_RESOURCE,
		
	INF_GATHER_SPEED,
	INF_ATTACK_SPEED,

	// INF_ECON_QUAD,
	// INF_BUILDINGS_QUAD,
	// INF_UNITS_QUAD,
	
	VISIBILITY,
};

