#pragma once
enum class InfluenceType : char {
	NONE,
	UNITS_NUMBER_PER_PLAYER,
	UNITS_INFLUENCE_PER_PLAYER,
	BUILDING_INFLUENCE_PER_PLAYER,
	RESOURCE_INFLUENCE,
	ECON_INFLUENCE_PER_PLAYER,
	ATTACK_INFLUENCE_PER_PLAYER,
	DEFENCE_INFLUENCE_PER_PLAYER,
};
