#pragma once
enum class InfluenceDataType : char {
	NONE = 0,
	UNITS_NUMBER_PER_PLAYER,
	UNITS_INFLUENCE_PER_PLAYER,
	BUILDING_INFLUENCE_PER_PLAYER,
	RESOURCE_INFLUENCE,
	
	GATHER_SPEED,
	ATTACK_SPEED,

	ECON_QUAD,
	BUILDINGS_QUAD,
	UNITS_QUAD,

	VISIBILITY
};
