#pragma once
enum class UnitMetric:char {
	COST_SUM=0,
	DEFENCE,
	DISTANCE_ATTACK,
	CLOSE_ATTACK,
	CHARGE_ATTACK,
	BUILDING_ATTACK
};

enum class BuildingMetric:char {
	COST_SUM=0,
	DEFENCE,
	DISTANCE_ATTACK,

	PROD_COST_SUM,
	PROD_DEFENCE,
	PROD_DISTANCE_ATTACK,
	PROD_CLOSE_ATTACK,
	PROD_CHARGE_ATTACK,
	PROD_BUILDING_ATTACK
};
