#pragma once
#include <cstdint>

#include "objects/resource/ResourceType.h"

enum class AiActionType : uint8_t {
	CREATE_WORKER,
	CREATE_UNIT,
	CREATE_BUILDING_OTHER,
	CREATE_BUILDING_DEFENCE,
	CREATE_BUILDING_RESOURCE,
	CREATE_BUILDING_TECH,
	CREATE_BUILDING_UNITS,
	UPGRADE_UNIT,
	UPGRADE_BUILDING,
	NONE
};

enum class AiActionResult : uint8_t {
	SUCCESS,
	NO_RESOURCES_SPECIFIC,
	NO_BUILDING_TO_DEPLOY,
	NO_POSITION_TO_BUILD,
	NO_BUILDINGS_OF_TYPE,
	NO_RESOURCE_BONUS,
	NO_UPGRADE_AVAILABLE,
	NONE
};

enum class AiOrderType : uint8_t {
	COLLECT_RESOURCE_0,
	COLLECT_RESOURCE_1,
	COLLECT_RESOURCE_2,
	COLLECT_RESOURCE_3,
	ATTACK_ECON,
	ATTACK_BUILDING,
	ATTACK_ARMY,
	DEFEND_ECON,
	DEFEND_BUILDING,
	DEFEND_ARMY,
	NONE
};

enum class AiOrderResult : uint8_t {
	SUCCESS,
	NO_RESOURCE_IN_RANGE,
	NO_CENTER_POSITION,
	NONE
};

