copy base.db base0.db
copy base.db base1.db
copy base.db base2.db
copy base.db base3.db
copy base.db base4.db
copy base.db base5.db
copy base.db base6.db
copy base.db base7.db
copy base.db base8.db
copy base.db base9.db
copy base.db base10.db
copy base.db base11.db
copy base.db base12.db
copy base.db base13.db
copy base.db base14.db
copy base.db base15.db
copy base.db base16.db
copy base.db base17.db
copy base.db base18.db
copy base.db base19.db
copy base.db base20.db
copy base.db base21.db
copy base.db base22.db
copy base.db base23.db
copy base.db base24.db
copy base.db base25.db
copy base.db base26.db
copy base.db base27.db
copy base.db base28.db
copy base.db base29.db
copy base.db base30.db

copy data.db data0.db
copy data.db data1.db
copy data.db data2.db
copy data.db data3.db
copy data.db data4.db
copy data.db data5.db
copy data.db data6.db
copy data.db data7.db
copy data.db data8.db
copy data.db data9.db
copy data.db data10.db
copy data.db data11.db
copy data.db data12.db
copy data.db data13.db
copy data.db data14.db
copy data.db data15.db
copy data.db data16.db
copy data.db data17.db
copy data.db data18.db
copy data.db data19.db
copy data.db data20.db
copy data.db data21.db
copy data.db data22.db
copy data.db data23.db
copy data.db data24.db
copy data.db data25.db
copy data.db data26.db
copy data.db data27.db
copy data.db data28.db
copy data.db data29.db
copy data.db data30.db

copy quicksave.db quicksave0.db
copy quicksave.db quicksave1.db
copy quicksave.db quicksave2.db
copy quicksave.db quicksave3.db
copy quicksave.db quicksave4.db
copy quicksave.db quicksave5.db
copy quicksave.db quicksave6.db
copy quicksave.db quicksave7.db
copy quicksave.db quicksave8.db
copy quicksave.db quicksave9.db
copy quicksave.db quicksave10.db
copy quicksave.db quicksave11.db
copy quicksave.db quicksave12.db
copy quicksave.db quicksave13.db
copy quicksave.db quicksave14.db
copy quicksave.db quicksave15.db
copy quicksave.db quicksave16.db
copy quicksave.db quicksave17.db
copy quicksave.db quicksave18.db
copy quicksave.db quicksave19.db
copy quicksave.db quicksave20.db
copy quicksave.db quicksave21.db
copy quicksave.db quicksave22.db
copy quicksave.db quicksave23.db
copy quicksave.db quicksave24.db
copy quicksave.db quicksave25.db
copy quicksave.db quicksave26.db
copy quicksave.db quicksave27.db
copy quicksave.db quicksave28.db
copy quicksave.db quicksave29.db
copy quicksave.db quicksave30.db

copy maps.db maps0.db
copy maps.db maps1.db
copy maps.db maps2.db
copy maps.db maps3.db
copy maps.db maps4.db
copy maps.db maps5.db
copy maps.db maps6.db
copy maps.db maps7.db
copy maps.db maps8.db
copy maps.db maps9.db
copy maps.db maps10.db
copy maps.db maps11.db
copy maps.db maps12.db
copy maps.db maps13.db
copy maps.db maps14.db
copy maps.db maps15.db
copy maps.db maps16.db
copy maps.db maps17.db
copy maps.db maps18.db
copy maps.db maps19.db
copy maps.db maps20.db
copy maps.db maps21.db
copy maps.db maps22.db
copy maps.db maps23.db
copy maps.db maps24.db
copy maps.db maps25.db
copy maps.db maps26.db
copy maps.db maps27.db
copy maps.db maps28.db
copy maps.db maps29.db
copy maps.db maps30.db