#pragma once

#define UNITS_NUMBER 25000

#define BUCKET_GRID_RESOLUTION 512
#define BUCKET_GRID_SIZE 1024

#define BUCKET_GRID_RESOLUTION_BUILD 128
#define BUCKET_GRID_RESOLUTION_ENEMY 64
#define BUCKET_GRID_RESOLUTION_RESOURCE 128
									
#define BUCKET_GRID_SIZE_BUILD 1024
#define BUCKET_GRID_SIZE_ENEMY 1024
#define BUCKET_GRID_SIZE_RESOURCE 1024


#define BENCH_LENGTH 200
#define BENCH_SKIP 2
#define BENCH_ENABLE false

#define MAX_PLAYERS 2
#define BUCKET_SET_NUMBER 4

#define STATE_SIZE 11

#define MAX_THREADS 4

#define MAX_SIZE_TYPES 10

#define DEFAULT_VECTOR_SIZE 10
